# Generated by Django 2.1.1 on 2018-10-29 13:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_title', models.CharField(max_length=200)),
                ('todo_contents', models.TextField(blank=True)),
                ('todo_expire_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('todo_is_prior', models.BooleanField(default=False)),
                ('todo_has_expire_date', models.BooleanField(default=False)),
                ('todo_is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
