# Generated by Django 2.1.1 on 2018-10-29 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_expire_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Expire date'),
        ),
    ]
